### PR TITLE
Auto-quoting

### LINKED ISSUE #6: Smarter auto-quoting
Firstly, thanks @weeman1337 for taking the time with this extension! Life got busy, and [my PR](https://github.com/nvim-telescope/telescope.nvim/pull/670) fell by the wayside 😂 

Anyway, one of the features I had started to implement in my PR was auto-quoting. For example in your extension, I can't search a string like `function create` unless I wrap it in quotes `'function create'` first.

I personally think spaces should be treated as part of the search query, unless command line options are needed, or quotes are part of the query you are trying to search...

| User's query: | Runs: | Note: |
| :--- | :--- | :--- |
| `function create` | `rg 'function create'` | Quotes not necessary |
| `func.*create` | `rg 'func.*create'` | Quotes not necessary |
| `it's a wonderful life` | `rg "it's a wonderful life"` | If only one quote instead of pair, quotes not necessary |
| `'function create'` | `rg 'function create'` | Don't auto-quote if they explicitly wrap with quotes |
| `"function create"` | `rg "function create"` | Don't auto-quote if they explicitly wrap with quotes |
| `-uu 'func.*create'` | `rg -uu 'func.*create'` | Don't auto-quote if they pass opts/args |
| `'func.*create' vendor` | `rg 'func.*create' vendor` | Don't auto-quote if they pass opts/args |

_Note: The `it's a wonderful life` example might be the most subjective and/or complicated one. The way I had implemented it in https://github.com/jesseleite/vim-agriculture was, if a single quote is used in the query at all, then don't auto-quote anything, and expect the user to wrap the query in quotes. It would be neat if it could detect single quotes vs quote pairs, but I understand if we skip on that one._

Curious on your thoughts? ❤️

### PR DESCRIPTION
**Pull request by weeman1337**
Closes #6

### CODE REVIEW

**Comment by jesseleite** [comment]
Slick! Will test later today hopefully 🎉

**Comment by nwaywood** [comment]
Hi, I know this would make the PR a bit more complicated but I had an idea so I thought I'd share to see what you think.

Another thing you can do with rg is specify a path at the end 

e.g. `rg foo /my/path`

It would be cool if this PR could also auto quote if there is a path supplied.

So we could write

`foo bar /my/path`

instead of

`'foo bar' /my/path`

All good if you think that makes it too complicated, just an idea :)

**Comment by nwaywood** [comment]
Thanks for this PR! I think its a good UX improvement.

But unless I'm missing something, I think this current implementation will cause a problem on a search like this:

`foo /my/path`

since that search doesn't start with `-`, `'` or `"` this search term would be incorrectly turned into 

`'foo /my/path'`

which would be unexpected behavior

**Comment by weeman1337** [comment]
Thanks @nwaywood for the feedback. I am unsure about that. Another point of view could be:

I want to grep code like `cd src/scripts`. `src/scripts` is a path → ~`rg cd src/scripts`.  
Which would be unexpected behaviour :wink: 

In the current PR the README shows the path example.

I would probably add another path quoting option after this PR.

**Comment by nwaywood** [comment]
Haha yeah thats true. But I think with an edge case like wanting the path to actually be within the search its reasonable to expect the user to need to add their own quotes.

> I would probably add another path quoting option after this PR.

Sounds good!

**Comment by nwaywood** [comment]
Btw the other use case I can think of that is possible is that rg lets you put flags after the search term, instead of before

e.g. `foo -t scala` instead of `-t scala foo`. Both of these are valid rg searches

I find myself doing this often because the way my brain would approach doing this is:
1. Search for what I want to find (e.g. `foo`)
2. See that the search results contain files I don't care about
3. Add the flag (e.g. `foo -t scala`)

**Comment by weeman1337** [comment]
@nwaywood good to learn about real use-cases.  
Could you think of any way how auto-quote can detect this?

From your example: `foo -t scala` vs `foo`, `-t`, `scala`

**Comment by nwaywood** [comment]
I am assuming that it is very hard to have a solution that handles all possible use cases (if it was easy, `rg` wouldn't ever require the quotes).

I guess the tricky balance with this feature will be deciding what use cases to support and which ones not to support, while also making sure not to have unexpected side effects (e.g. like the `foo /my/path` example I gave above).

Maybe only enable auto quoting if no `"`, `'`, `-` or a path is found anywhere is the query?

**Comment by jesseleite** [comment]
Also...
 
> I find myself doing this often because the way my brain would approach doing this is:
> 
> 1. Search for what I want to find (e.g. `foo`)
> 2. See that the search results contain files I don't care about
> 3. Add the flag (e.g. `foo -t scala`)

💡 What about also providing a telescope mapping that would let you wrap the entire contents of the prompt in quotes. Imagine this...

1. You search for `foo`.
2. You see there are paths/files you don't care about.
3. You hit `CTRL+'` or some mapping that will automatically wrap `'foo'` in quotes and leave your cursor position at end.
4. You add your args/params, etc.

**Comment by weeman1337** [comment]
I am going to merge this now because it is working.  
I appreciate all ideas here. It was a very productive discussion :+1: 

Follow up tasks:

- #15
- #16

**Pull request merged**
